spring.application.name=demo
spring.data.mongodb.authentication-database = admin
# spring.data.mongodb.uri=mongodb://root:F8jtnzkF6Xvt@127.0.0.1:27017/formation?authSource=admin
# spring.data.mongodb.uri=mongodb+srv://root:
# spring.data.mongodb.username=guiras086_db_user
# spring.data.mongodb.password=4HSSj3l1LAEQPKG8
spring.data.mongodb.uri=mongodb+srv://guiras086_db_user:4HSSj3l1LAEQPKG8@cluster0.z6c5h95.mongodb.net/formation?retryWrites=true&w=majority
spring.jpa.hibernate.ddl-auto=create
app.secret-key=DEFRGTHYJU25DCFV1412GTKLJKBNFRHY




#mail configuration
spring.mail.host=smtp.ionos.fr
spring.mail.port=587
spring.mail.username=contact@essikia.com
spring.mail.password=C@nstance2025
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.ionos.fr
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
# supabase variable environnement
supabase.url=https://lfhrouslibhmugifotkd.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmaHJvdXNsaWJobXVnaWZvdGtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNjk3MjUsImV4cCI6MjA1NTg0NTcyNX0.YmvhJG8w0RlESZsFhG37rFBRNowCQU5OVcZYBMxL0vM
supabase.bucket=essikia_fichier
server.tomcat.max-swallow-size=200MB

# stripe secret key
# Test key


# prod
